"""add title platform and transcribed_text to film

Revision ID: 397b6181db45
Revises: 561eb74a07e7
Create Date: 2025-11-25 01:28:39.154000

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '397b6181db45'
down_revision: Union[str, Sequence[str], None] = '561eb74a07e7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('films', sa.Column('title', sa.String(), nullable=True))
    op.add_column('films', sa.Column('platform', sa.String(), nullable=True))
    op.add_column('films', sa.Column('transcribed_text', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('films', 'transcribed_text')
    op.drop_column('films', 'platform')
    op.drop_column('films', 'title')
    # ### end Alembic commands ###
