"""remove unique constraint from job film_id

Revision ID: 561eb74a07e7
Revises: 43f340da46ed
Create Date: 2025-11-25 01:16:48.260879

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '561eb74a07e7'
down_revision: Union[str, Sequence[str], None] = '43f340da46ed'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('jobs_film_id_key'), 'jobs', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('jobs_film_id_key'), 'jobs', ['film_id'], postgresql_nulls_not_distinct=False)
    # ### end Alembic commands ###
